src/MyDrilling.Web/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyDrilling.Web.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult GetDrillDownMenu()
        {
            return ViewComponent("DrillDownMenu");
        }
    }
}

src/MyDrilling.Web/Controllers/UserprofileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyDrilling.Core.Entities.Enquiry;
using MyDrilling.Core.Entities.Subscription;
using MyDrilling.Infrastructure.Data;
using MyDrilling.Web.Models.Userprofile;
using MyDrilling.Web.UserDetails;
using UserSetting = MyDrilling.Core.Entities.UserSetting;

namespace MyDrilling.Web.Controllers
{
    public class UserprofileController : Controller
    {
        private readonly ILogger<UserprofileController> _logger;
        private readonly MyDrillingDb _db;

        public UserprofileController(ILogger<UserprofileController> logger, MyDrillingDb db)
        {
            _logger = logger;
            _db = db;
        }
        public IActionResult Index()
        {
            var user = HttpContext.GetCurrentUser();
            var userProfile = new UserProfileViewModel
            {
                FullName = user.DisplayName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                CompanyName = user.RootCustomer.Name,
                EmailAddress = user.Email,
                PhoneNumber = user.PhoneNumber,
                Upn = user.Upn

            };
            return View(userProfile);
        }

        public ActionResult MyPreferences()
        {
            return ViewComponent("MyPreferences");
        }

        public ActionResult MyNotifications()
        {
            return ViewComponent("MyNotifications");
        }

        public ActionResult MyTimeZone()
        {
            return ViewComponent("MyTimeZone");
        }

        [HttpPost]
        public async Task<ActionResult> SubmitMyTimeZone(TimeZoneViewModel model)
        {
            var user = HttpContext.GetCurrentUser();
            var currentTimeZone = user.GetTimeZoneInfo();
            if (currentTimeZone.Id != model.SelectedTimeZone)
            {
                var timeZoneRow = await _db.UserSettings.FirstOrDefaultAsync(x => x.UserId == user.Id && x.Key == UserSetting.Keys.SelectedTimezone);
                if (timeZoneRow != null)
                {
                    timeZoneRow.Value = model.SelectedTimeZone;
                }
                else
                {
                    _db.UserSettings.Add(new UserSetting
                    {
                        UserId = user.Id,
                        Key = UserSetting.Keys.SelectedTimezone,
                        Value = model.SelectedTimeZone
                    });
                }
                await _db.SaveChangesAsync();
            }
            return MyTimeZone();
        }


        [HttpPost]
        public async Task<ActionResult> SubmitMyPreferences(MyPreferencesViewModel model)
        {
            if (model.SelectedPreferences == null)
                model.SelectedPreferences = new List<string>();
            var user = HttpContext.GetCurrentUser();
            var currentShowUnreadEnquiries = user.GetShowUnreadEnquiries();
            var showUnreadOption = model.PreferencesOptions.FirstOrDefault(x => x.OptionValue == UserSetting.Keys.ShowUnreadEnquiries);
            if (showUnreadOption != null && currentShowUnreadEnquiries != showUnreadOption.Selected)
            {
                //update user preference for ShowUnreadEnquiries
                var showUnreadEnquiriesRow = await _db.UserSettings.FirstOrDefaultAsync(x => x.UserId == user.Id && x.Key == UserSetting.Keys.ShowUnreadEnquiries);
                if (showUnreadEnquiriesRow != null)
                {
                    showUnreadEnquiriesRow.Value = showUnreadOption.Selected.ToString();
                    
                }
                else
                {
                    _db.UserSettings.Add(new UserSetting
                    {
                        UserId = user.Id,
                        Key = UserSetting.Keys.ShowUnreadEnquiries,
                        Value = showUnreadOption.Selected.ToString()
                    });
                }
                await _db.SaveChangesAsync();
            }

            var currentDontAllowOthersToAddMeToEnquiries = user.GetDoNotAllowOthersToAddMeToEnquiries();
            var dontAllowOthersOption = model.PreferencesOptions.FirstOrDefault(x => x.OptionValue == UserSetting.Keys.DoNotAllowOthersToAddMeToEnquiries);
            if (dontAllowOthersOption != null && currentDontAllowOthersToAddMeToEnquiries != dontAllowOthersOption.Selected)
            {
                //update user preference for DoNotAllowOthersToAddMeToEnquiries
                var dontAllowOthersRow = await _db.UserSettings.FirstOrDefaultAsync(x => x.UserId == user.Id && x.Key == UserSetting.Keys.DoNotAllowOthersToAddMeToEnquiries);
                if (dontAllowOthersRow != null)
                {
                    dontAllowOthersRow.Value = dontAllowOthersOption.Selected.ToString();
                }
                else
                {
                    _db.UserSettings.Add(new UserSetting
                    {
                        UserId = user.Id,
                        Key = UserSetting.Keys.DoNotAllowOthersToAddMeToEnquiries,
                        Value = dontAllowOthersOption.Selected.ToString()
                    });
                }
                await _db.SaveChangesAsync();
            }

            return MyPreferences();
        }

        [HttpPost]
        public async Task<ActionResult> SubmitMyNotifications(MyNotificationsViewModel model)
        {
            var checkedCommonSubscriptions = GetCheckedSubscriptions(model, NotifyMeType.CommonSubscription);
            var checkedRigFilterSubscriptions = GetCheckedSubscriptions(model, NotifyMeType.RigFilters);
            var checkedEnquiryTypeFilterSubscriptions = GetCheckedSubscriptions(model, NotifyMeType.EnquiryTypeFilters);
            //get current subscriptions for user
            var user = HttpContext.GetCurrentUser();
            var dbUser = await _db.Users
                .Include(x => x.SubscriptionSettings)
                .Include(x => x.SubscriptionRigFilters)
                .Include(x => x.SubscriptionEnquiryTypeFilters)
                .FirstOrDefaultAsync(x => x.Id == user.Id);
            var deletedCommonSubscriptions = dbUser.SubscriptionSettings.Where(s =>
                    checkedCommonSubscriptions.All(x => (int)s.SubscriptionType != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var deleted in deletedCommonSubscriptions)
            {
                var itemToDelete = dbUser.SubscriptionSettings.FirstOrDefault(x => x.SubscriptionType == deleted.SubscriptionType);
                var dbItem = await _db.Subscription_UserSettings.FirstOrDefaultAsync(x => x.Id == itemToDelete.Id);
                _db.Subscription_UserSettings.Remove(dbItem);
            }
            var newCommonSubscriptions = checkedCommonSubscriptions
                .Where(x => dbUser.SubscriptionSettings.All(s => (int)s.SubscriptionType != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var newCommon in newCommonSubscriptions)
            {
                _db.Subscription_UserSettings.Add(new Core.Entities.Subscription.UserSetting
                {
                    UserId = dbUser.Id,
                    SubscriptionType = (SubscriptionType)int.Parse(newCommon.OptionValue),
                    Created = DateTime.UtcNow
                });
            }

            var deletedRigFilterSubscriptions = dbUser.SubscriptionRigFilters.Where(s =>
                    checkedCommonSubscriptions.All(x => s.RigId != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var deleted in deletedRigFilterSubscriptions)
            {
                var itemToDelete = dbUser.SubscriptionRigFilters.FirstOrDefault(x => x.RigId == deleted.RigId);
                var dbItem = await _db.Subscription_RigFilters.FirstOrDefaultAsync(x => x.Id == itemToDelete.Id);
                _db.Subscription_RigFilters.Remove(dbItem);
            }
            var newRigFilterSubscriptions = checkedRigFilterSubscriptions
                .Where(x => dbUser.SubscriptionRigFilters.All(s => s.RigId != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var newRigFilter in newRigFilterSubscriptions)
            {
                _db.Subscription_RigFilters.Add(new RigFilter
                {
                    UserId = dbUser.Id,
                    RigId = int.Parse(newRigFilter.OptionValue),
                    Created = DateTime.UtcNow
                });
            }

            var deletedEnquiryTypeFilterSubscriptions = dbUser.SubscriptionEnquiryTypeFilters.Where(s =>
                    checkedEnquiryTypeFilterSubscriptions.All(x => (int)s.Type != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var deleted in deletedEnquiryTypeFilterSubscriptions)
            {
                var itemToDelete = dbUser.SubscriptionEnquiryTypeFilters.FirstOrDefault(x => x.Type == deleted.Type);
                var dbItem = await _db.Subscription_EnquiryTypeFilters.FirstOrDefaultAsync(x => x.Id == itemToDelete.Id);
                _db.Subscription_EnquiryTypeFilters.Remove(dbItem);
            }
            var newEnquiryTypeFilterSubscriptions = checkedEnquiryTypeFilterSubscriptions
                .Where(x => dbUser.SubscriptionEnquiryTypeFilters.All(s => (int)s.Type != int.Parse(x.OptionValue)))
                .Select(x => x);
            foreach (var newEnquiryTypeFilter in newEnquiryTypeFilterSubscriptions)
            {
                _db.Subscription_EnquiryTypeFilters.Add(new EnquiryTypeFilter
                {
                    UserId = dbUser.Id,
                    Type = (TypeInfo.Type)int.Parse(newEnquiryTypeFilter.OptionValue),
                    Created = DateTime.UtcNow
                });

src/MyDrilling.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using System.Reflection
@using Microsoft.AspNetCore.Mvc.Rendering
@using MyDrilling.Web.UserDetails
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(ViewData["Title"] + " / MHWirth myDrilling")</title>
    <environment include="Development">
        <link rel="stylesheet" href="/css/Site.css" />
        <link rel="stylesheet" href="/css/admin/Admin.css" />
        <link rel="stylesheet" href="/css/jquery-ui-1.8.16.custom.css" />
        <script src="/js/autocomplete.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="/css/Site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="/css/admin/Admin.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="/css/jquery-ui-1.8.16.custom.min.css" asp-append-version="true" />
        <script src="/js/autocomplete.min.js" asp-append-version="true"></script>
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    @Html.Raw(JavaScriptSnippet.FullScript.Replace("https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js", "https://js.monitor.azure.com/scripts/b/ai.2.min.js"))
</head>
<body>
<style>
    #main {
        margin-right: 0;
    }
    .stdForm {
        padding-top: 5px;
    }
    .stdForm label {
        min-width: 80px;
        line-height: 20px;
    }
    .stdForm #show-all {
        margin: 4px 0;
    }
    .stdTable .buttonSubmit {
        padding: 2px 4px;
    }
    h1 > .md-button {
        margin-left: 10px;
    }
</style>
<div id="wrapper">

    <div id="admin">
        <div id="header">
            <a id="akerSolutions" href="/" target="_blank" title="Home">
                <img src="/graphics/myDrilling.png?v=1.5.2" alt="myDrilling" title="myDrilling" width="250" height="81"/>
            </a>
            <a id="myDrilling" href="https://www.mhwirth.com" title="Go to MHWirth">
                <img src="/graphics/MH_wirth_logo.png?v=1.5.2" alt="Go to MHWirth" title="Go to MHWirth" width="150" height="56"/>
            </a>
            <a href="/" title="Home" id="return_to_my_drilling_button">
                <img src="@Url.Content("~/graphics/returnToMyDrilling.png?v=1.5.2")">
            </a>
        </div>

        <div>
            <div id="welcome"><em>@LanguageConstants.Welcome:</em> @Context.GetCurrentUser().GetDisplayName()<em>&nbsp; @Context.GetCurrentUser().RootCustomer?.Name </em></div>
            <ul id="nav-top">
                <li>
                    <a asp-controller="Account" asp-action="SignOut">Sign out</a>
                </li>
                <li>
                    @Html.ActionLink("My profile", "Index", "Userprofile", null, new {@class = "popup-ajax", @id = "userProfileLink"})
                </li>
                @*<li>@Html.ActionLink("Help", "Index", "Home", null, new { id = "firsttimeuser", @class = "popup-ajax" })</li>

                    <li>
                        @Html.ActionLink("Analytics", "Index", "Home", null, new Dictionary<string, object> { { "class", "lnkAll" } })
                    </li>

                    <li>
                        @Html.ActionLink("Trends", "Index", "Home", null, new Dictionary<string, object> { { "class", "lnkAll" } })
                    </li>*@

                <li><a title="About MHWirth" href="https://www.mhwirth.com" target="_blank">About MHWirth</a></li>
            </ul>
        </div>

        <div id="drilldown">
            @*@Html.Action("Index", "Menu")*@

        </div>
        <div id="pendingTickets"></div>
        <div id="content" class="@((string.IsNullOrEmpty(ViewBag.OuterClass)) ? "subpage" : ViewBag.OuterClass)">
            <div id="main">
                <div id="mainContainer3">
                    <div id="mainContainer1">
                        @if (IsSectionDefined("RightBar"))
                        {
                            <div id="mainRight">
                                <div id="mainWithRightBar">
                                    <div id="mainWithRightBarInner">
                                        @RenderBody()
                                    </div>
                                </div>
                                <div id="rightBar">
                                    <div class="inner">
                                        @RenderSection("RightBar", false)
                                    </div>
                                </div>
                                <div class="clear"></div>
                            </div>
                        }
                        else
                        {
                            <div id="mainContent">
                                @RenderBody()
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div id="left">
                <div id="leftMenu">

                    <ul id="mainMenu">
                        <li>@Html.ActionLink("Overview", "Index", "Home", new {area = "Admin"}, new Dictionary<string, object>
                            {
                                {"hidefocus", "true"},
                                {"style", "outline:none;"},
                                {"class", ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "current" : ""}
                            })</li>
                        @if (Context.GetCurrentUserRoles().IsSystemAdmin() || Context.GetCurrentUserRoles().IsUserAdmin())
                        {
                            <li>@Html.ActionLink("Users", "Index", "Users", new {area = "Admin"}, new Dictionary<string, object>
                                {
                                    {"hidefocus", "true"},
                                    {"style", "outline:none;"},
                                    {"class", ViewContext.RouteData.Values["controller"].ToString() == "Users" ? "current" : ""}
                                })</li>
                        }
                        @if (Context.GetCurrentUserRoles().IsSystemAdmin() || Context.GetCurrentUserRoles().IsUserAdmin())
                        {
                            <li>@Html.ActionLink("Access profiles", "Index", "AccessProfiles", new {area = "Admin"}, new Dictionary<string, object>
                                {
                                    {"hidefocus", "true"},
                                    {"style", "outline:none;"},
                                    {"class", ViewContext.RouteData.Values["controller"].ToString() == "AccessProfiles" ? "current" : ""}
                                })</li>
                        }
                        @if (Context.GetCurrentUserRoles().IsSystemAdmin() || Context.GetCurrentUserRoles().IsCustomerAdmin())
                        {
                            <li>@Html.ActionLink("Customers", "Index", "Customers", new {area = "Admin"}, new Dictionary<string, object>
                                {
                                    {"hidefocus", "true"},
                                    {"style", "outline:none;"},
                                    {"class", ViewContext.RouteData.Values["controller"].ToString() == "Customers" ? "current" : ""}
                                })</li>
                        }
                        @if (Context.GetCurrentUserRoles().IsSystemAdmin())
                        {
                            <li>@Html.ActionLink("Facilities", "Index", "Facilities", new {area = "Admin"}, new Dictionary<string, object>
                                {
                                    {"hidefocus", "true"},
                                    {"style", "outline:none;"},
                                    {"class", ViewContext.RouteData.Values["controller"].ToString() == "Facilities" ? "current" : ""}
                                })</li>
                        }

                        @*@if (userSession.HasAccessRight(Process.Admin, ProcessRight.SysAdmin))
                            {
                                <li>@Html.ActionLinkIsActive("Banner", "Index", "Support", "Support", ViewData["ActivePage"],"Admin")</li>
                                <li>@Html.ActionLinkIsActive("Errorlog", "Search", "Errorlog", "Search", ViewData["ActivePage"],"Admin")</li>
                                <li>@Html.ActionLinkIsActive("User operations", "Index", "Ticket", "Ticket", ViewData["ActivePage"],"Admin")</li>
                                <li>@Html.ActionLinkIsActive(Captions.AccessReport, "Index", "UserAccessReport", "UserAccess", ViewData["ActivePage"], "Admin")</li>
                                <li>@Html.ActionLinkIsActive(Captions.Facilities, "Index", "Facility", "Facilities", ViewData["ActivePage"],"Admin")</li>
                            }*@
                    </ul>
                </div>
            </div>
            <div id="footer">
                <span style="float: right;">
                    @Html.ActionLink("Terms and conditions", "TermsAndConditions", "Home", null, new {@class = "popup-ajax", title = "Terms and conditions"})
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="mailto:support@mydrilling.com?subject=myDrilling:%20New%20ideas" title="Report new ideas">Report new ideas</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mailto:support@mydrilling.com?subject=myDrilling%20support" title="Report a problem">Report a problem</a>
                </span>
                <p>
                    myDrilling &copy; @(DateTime.Now.Year + " MHWirth")&nbsp;&nbsp;Version&nbsp;@Assembly.GetExecutingAssembly().GetName().Version
                </p>
            </div>
        </div>
        <div class="clear">
        </div>
    </div>
</div>
<div id="adminDialog"></div>
<script>
    $(function() {
        $(".popup-ajax").each(function() {
            addFancyBox($(this));
        });
        var sessionCheck = setInterval(function() {
                $.ajax({
                    url: "/home/issessionalive",
                    success: function(result) {
                        if (console)
                            console.log(result.message);
                    },
                    error: function(xhr) {
                        if (xhr.status == '408') {
                            clearInterval(sessionCheck);
                            var response = xhr.responseJSON;
                            var messageHtml =
                                $('<div class="session-expired-message"><h2>' + response.message + '</h2></div>')
                                    .appendTo($('body'));
                            messageHtml.fancybox({
                                'overlayOpacity': 0.92,
                                'centerOnScroll': true,
                                'afterClose': function() {
                                    location.reload();
                                    return;
                                }
                            }).trigger('click');
                        }
                    }
                });
            },
            20000);
    });

    function addFancyBox(element) {
        element.fancybox({
            'padding': 0,
            'overlayOpacity': 0.92,
            'centerOnScroll': true,
            'autoDimensions': true,
            'titleShow': false,
            'type': 'ajax',
            'onStart': function() {
                $("#fancybox-close").addClass('fancyclose');
            }
        });
    }
</script>
@RenderSection("Scripts", false)
</body>
</html>

src/MyDrilling.Web/Areas/Admin/Views/Shared/_PopupLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(ViewData["Title"] + " / MHWirth myDrilling")</title>
    <link rel="stylesheet" href="/css/jquery-ui-1.8.16.custom.css" />
    <link rel="stylesheet" href="/css/Site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css" />
</head>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    @RenderBody()
</body>
</html>